### ISSUE TITLE
load_operations_to_gcs task is failing with No such file or directory: '/home/airflow/gcs/data/8981-9042-operations.txt'

### ISSUE THREAD

**Issue by medvedev1088** [stellar/stellar-etl-airflow#53]
Please advise on what can be the root cause. This also happens with load_transactions_to_gcs and load_trades_to_gcs for all dates.

Full Composer log below:

```
[2020-12-14 16:28:11,904] {taskinstance.py:882} INFO - Starting attempt 6 of 6
[2020-12-14 16:28:11,904] {taskinstance.py:883} INFO -
--------------------------------------------------------------------------------
[2020-12-14 16:28:11,925] {taskinstance.py:902} INFO - Executing <Task(PythonOperator): load_operations_to_gcs> on 2015-10-01T05:50:00+00:00
[2020-12-14 16:28:11,936] {standard_task_runner.py:54} INFO - Started process 23171 to run task
[2020-12-14 16:28:11,956] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'history_archive_export', 'load_operations_to_gcs', '2015-10-01T05:50:00+00:00', '--job_id', '10272', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/history_archive_dag.py', '--cfg_path', '/tmp/tmpu8xs_9j4']
[2020-12-14 16:28:11,960] {standard_task_runner.py:78} INFO - Job 10272: Subtask load_operations_to_gcs
[2020-12-14 16:28:12,569] {logging_mixin.py:112} INFO - Running <TaskInstance: history_archive_export.load_operations_to_gcs 2015-10-01T05:50:00+00:00 [running]> on host airflow-worker-66bc55b486-bct78
[2020-12-14 16:28:12,702] {build_load_task.py:86} INFO - <class 'dict'>
[2020-12-14 16:28:12,703] {build_load_task.py:91} INFO - Pulling filename from task export_operations_task; result is 8981-9042-operations.txt
[2020-12-14 16:28:12,780] {build_load_task.py:98} INFO - Attempting to upload local file at /home/airflow/gcs/data/8981-9042-operations.txt to Google Cloud Storage path exported/operations/8981-9042-operations.txt in bucket stellar-testing-us-0
[2020-12-14 16:28:12,961] {taskinstance.py:1152} ERROR - [Errno 2] No such file or directory: '/home/airflow/gcs/data/8981-9042-operations.txt'
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 985, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 113, in execut
    return_value = self.execute_callable(
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 118, in execute_callabl
    return self.python_callable(*self.op_args, **self.op_kwargs
  File "/home/airflow/gcs/dags/stellar_etl_airflow/build_load_task.py", line 99, in upload_to_gc
    success = attempt_upload(local_filepath, gcs_filepath, bucket_name
  File "/home/airflow/gcs/dags/stellar_etl_airflow/build_load_task.py", line 49, in attempt_uploa
    if os.path.getsize(local_filepath) > 10 * 2 ** 20
  File "/opt/python3.6/lib/python3.6/genericpath.py", line 50, in getsiz
    return os.stat(filename).st_siz
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/data/8981-9042-operations.txt
[2020-12-14 16:28:12,964] {taskinstance.py:1196} INFO - Marking task as FAILED. dag_id=history_archive_export, task_id=load_operations_to_gcs, execution_date=20151001T055000, start_date=20201214T162811, end_date=20201214T162812
[2020-12-14 16:28:16,336] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by Isaiah-Turner** [comment]
It looks like the export tasks aren't outputting files to the correct location, so the load tasks can't pick them up. There's a few reasons why this could happen. 

1. Does the export task correctly export information? Here's how you can test this: 
    - First, run `kubectl get pods --all-namespaces`. Look for a pod that starts with `airflow-worker`. 
    - Then, run `kubectl -n composer-1-6-0-airflow-example-namespace exec -it airflow-worker-1a2b3c-x0yz -c airflow-worker -- /bin/bash` to get inside the worker
    - Run `airflow test history_archive_export get_ledger_range_from_times 2020-07-18`, then run `airflow test history_archive_export export_ledgers_task 2020-07-18`.
    - The files should appear in `/home/airflow/gcs/data/`. If they appear somewhere else (like in `/home/airflow/etlData/`) see the steps below.
2. Did you remember to [add the poststart script](https://github.com/stellar/stellar-etl-airflow#modify-kubernetes-config-for-airflow-workers) to your airflow workers? 
3. Did you change the local_output_path variable? If so, were those changes reflected in the poststart script?

If you run into any issues with testing, let me know.

**Comment by debnil** [comment]
@medvedev1088 - just making sure you see the above response.

**Comment by acharb** [comment]
closing this since it's been resolved based off email conversation
